### PR TITLE
JSON response to thread controller

### PR DESCRIPTION
**Pull request by ChristineRemirez**
## Purpose

Proper HTTP response to controller actions.

## Approach

- Add JSON response to threads controller.

### CODE REVIEW

**Comment by Thavarshan** [comment]
Hi @ChristineRemirez, Thanks for the contribution but some of your code seems to have style issues. Could you please correct them and update your PR please?

**Comment by ChristineRemirez** [comment]
Oh sure. I'll fix them. I'm kinda new to this. This is my first contribution btw.

**Comment by Thavarshan** [comment]
> Oh sure. I'll fix them. I'm kinda new to this. This is my first contribution btw.

Congratulations on your first contribution! Seems likely that your additions will be merged but that depends on @pasanks. This project is sort of like an exercise project, would you mind if we ask you to contribute to our other projects instead of this one.

**Comment by ChristineRemirez** [comment]
Oh, I didn't know. I'm sorry about that. I'll stop now.

**Comment by ChristineRemirez** [comment]
> Oh, I didn't know. I'm sorry about that. I'll stop now.

It's quite alright, we'll merge your PR since it doesn't have so much of an impact, but we'd like you to still contribute though. You are welcome to contribute to any of my or @pasanks projects.

**Comment by Thavarshan** [comment]
> Oh, I didn't know. I'm sorry about that. I'll stop now.

It's quite alright, we'll merge your PR since it doesn't have much of an impact on our current work. You are more than welcome to contribute to either mine or @pasanks other **GitHub** projects.

**Review by Thavarshan — APPROVED** [review]

**Pull request merged**
